version: '3.8'

services:
  cache:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=sertton
    volumes: 
      - cache:/data
  app:
    build: .
    container_name: http-pandas
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules

volumes:
 cache:
    driver: local
