export type StatusMessage =
  | 'Continue'
  | 'Switching Protocols'
  | 'Processing'
  | 'Early hints'
  | 'OK'
  | 'Created'
  | 'Accepted'
  | 'Non-Authoritative Information'
  | 'No Content'
  | 'Reset Content'
  | 'Partial Content'
  | 'Multi-Status'
  | 'Already Reported'
  | 'IM Used'
  | 'Multiple Choices'
  | 'Moved Permanently'
  | 'Found'
  | 'See Other'
  | 'Not Modified'
  | 'Use Proxy'
  | 'Switch Proxy'
  | 'Temporary Redirect'
  | 'Permanent Redirect'
  | 'Bad Request'
  | 'Unauthorized'
  | 'Payment Required'
  | 'Forbidden'
  | 'Not Found'
  | 'Method Not Allowed'
  | 'Not Acceptable'
  | 'Proxy Authentication Required'
  | 'Request Timeout'
  | 'Conflict'
  | 'Gone'
  | 'Length Required'
  | 'Precondition Failed'
  | 'Payload Too Large'
  | 'URI Too Long'
  | 'Unsupported Media Type'
  | 'Range Not Satisfiable'
  | 'Expectation Failed'
  | "I'm a teapot"
  | 'Unprocessable Entity'
  | 'Locked'
  | 'Failed Dependency'
  | 'Upgrade Required'
  | 'Precondition Required'
  | 'Too Many Requests'
  | 'Request Header Fields Too Large'
  | 'No response'
  | 'Blocked by Windows Parental Controls'
  | 'Unavailable For Legal Reasons'
  | 'HTTP Request Sent to HTTPS Port'
  | 'Token expired/invalid'
  | 'Client Closed Request'
  | 'Internal Server Error'
  | 'Not Implemented'
  | 'Bad Gateway'
  | 'Service Unavailable'
  | 'Gateway Timeout'
  | 'HTTP Version Not Supported'
  | 'Variant Also Negotiates'
  | 'Insufficient Storage'
  | 'Loop Detected'
  | 'Not Extended'
  | 'Network Authentication Required'
  | 'Web Server is Down'
  | 'Connection Timed Out'
  | 'Origin Is Unreachable'
  | 'SSL Handshake Failed'
  | 'Site Frozen'
  | 'Network Connect Timeout Error'
